services:

  db:
    build: ./db
    image: postgres
    container_name: db-con
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demodb

  adminer:
    build: ./adminer
    image: adminer
    container_name: adminer-con
    depends_on:
      - db
    ports:
      - 8080:8080
